miykael/atlasreader

notebooks/mni_atlas_reader.ipynb

This fix references #32. The notebook works when run from its new directory.

Fixed paths and create_output() in example notebook

---

atlasreader/atlasreader.py

- df outputs had an `Unnamed: 0` column due to the `.to_csv` command
- `index=False` was included in the respective lines to fix it

fix pandas df output

---

atlasreader/atlasreader.py
atlasreader/tests/test_atlasreader.py
notebooks/atlasreader.ipynb

Hi all, 
I've added the option of customizing the brain plots, as discussed in #44. `create_output` now has two additional optional arguments, `glass_plot_kws` and `stat_plot_kws`. If they are set (e.g., `glass_plot_kws={'black_bg': False}), these parameters are passed onto the plotting functions within `create_output`. Otherwise, the plots will be shown exactly as how we've had them before. So, this allows users to customize the defaults, if desired, that we've already set. This PR also includes an update to the demo notebook demonstrating this customization capability. 
@rmarkello: This PR does not include any changes to the CLI. I was wondering if you could take a look at how we could best implement this?

Additional plotting options added to create_ouput

---

atlasreader/atlasreader.py

Closes https://github.com/miykael/atlasreader/issues/46.
This PR changes the `process_img` output so that the returned cluster image is always ordered by cluster size.

ENH: orders clusters by cluster size

---

atlasreader/atlasreader.py
atlasreader/cli.py
atlasreader/tests/test_atlasreader.py
atlasreader/tests/test_cli.py
notebooks/atlasreader.ipynb

A two-in-one since I was editing `atlasreader.cli`, anyway.
Closes #43. This PR modifies all functions that use the `cluster_extent` parameter to make it a _required_ parameter, and updates tests accordingly. 
Closes #53. This modifies the reading of user-specifies `atlas`es from the command line so that they are automatically converted to a lowercase string (regardless of user specification), reducing the need to specify casing in the accepted list of atlases.

REF: Cluster extent not optional

---

atlasreader/atlasreader.py

I prefer the `symmetric_cbar` value to be `False`. Otherwise it can lead to misleading colorlabels:
What do others think?
I would of course love to have the vmax for positive and negative to be different, but I don't think that this can be done at the moment.

ENH: sets symmetric_cbar to false

---

atlasreader/atlasreader.py

Closes #39.
Adds `float_format` parameters to `df.to_csv` calls when gerating peak + cluster CSV files, resolving issue of significant digits + rounding.

ENH: Fixes float format in CSV output

---

atlasreader/atlasreader.py
atlasreader/tests/test_atlasreader.py

Closes #61.
Adds checks to ensure:
1. Provided `voxel_thresh` parameter isn't larger than the maximum value in the provided stat map (this would otherwise trigger a warning), and
2. An empty statmap (potentially due to thresholding + clustering) doesn't raise any errors.

FIX: Fixes error when provided statmaps contains no clusters

---

atlasreader/atlasreader.py

Simple fixes for #68. Just changed the documentation for the `filename` parameter in `create_output`, and changed default output prefix to `"atlasreader"`. 
Now that I think about it, the use of `filename` is maybe a misnomer. Perhaps we could change it to `img` to show that it is _not_ just a file name, but can also be any `NIfTI-like` object. Thoughts?

ENH: doc fixes and changed default files to have atlasreader as prefix

---

atlasreader/atlasreader.py

I just had 15min confusion with the `min_cluster_size` parameter and the volume listed in the tables, until I realized that:
- `min_cluster_size` expects number of voxels
- `volume` in the tables represents mm^3
I had voxels of 3x3x3mm, i.e. 27mm per voxel, and clusters with volumes of 216 mm^3. I was so confused why `atlasreader` crashed with ``min_cluster_size`` higher than 8, until I understood the unit difference.
I therefore propose that we use the same unit for both parameters or clarify that volume is in mm^3 (which I try with this PR). What do others think about this issue?
We could also add another variable to the table, called 'volume_vox'?

Rename 'volume' to 'volume_mm' to clarify unit

---

atlasreader/tests/test_atlasreader.py

This PR adds a test to check if the tables create the output that we expect them to create. The checksum that is included in the test is based on the current output and might need to be adapted if we find future bugs. But like this, we will always know when the table output changes.

ENH: adds test to check table output

---

atlasreader/atlasreader.py

It seems that the `min_cluster_size` parameter was exclusive, i.e. if a cluster size of 100mm^3 was specified, then clusters of 100mm^3 were not shown. I assume that this is due to some rounding issue and comparisons of floats issue.
Reducing the `min_region_size` value of `nilearn.regions`'s `connected_regions` function by `1e-8` was in my case enough to take care of this.

ENH: make cluster extent inclusive

---

atlasreader/atlasreader.py

While running `atlasreader` in my system, I've encountered multiple `numpy` warnings:
```
~/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:26:
RuntimeWarning: invalid value encountered in reduce
return umr_maximum(a, axis, None, out, keepdims)
```
This PR takes care of these.
I'm not sure why `image.index_img(img_4d, 0)` threw this error if the `img_4d` originally was only a 3D image, but the changes take care of this error.
The second correction is more important. I had to add a `nan_to_num` transformation, as some niftis might include `nan`. Especially the ones from SPM. This means that the `if` condition `voxel_thresh > np.abs(stat_img.get_data()).max()` was always `False`,  the moment `stat_img` contains `nan`.

ENH: removes some more numpy warnings

---

atlasreader/cli.py
setup.py

Closes #37.
Adds ability to query atlases with a single xyz coordinate (in MNI space) and get a slightly-formatted output of the labels associated with that coordinate for all available (or requested) atlases.
Example usage:
```bash
$ queryatlas 10.3 -20.1 34.8
Atlas                     Label                    
==========                ==========               
aal                       Cingulum_Mid_R
desikan_killiany          Right-Cerebral-White-Matter
destrieux                 Right-Cerebral-White-Matter
harvard_oxford             0% no_label
juelich                   73% WM_Cingulum_R
31% WM_Callosal_body
neuromorphometrics        Right_Cerebral_White_Matter
```
Still need to add tests, but wanted to open a PR to see if you have feedback on the idea / implementation / organization.

WIP, ENH: Adds `queryatlas` command for coordinates of interest

---

.gitignore
atlasreader/__init__.py
atlasreader/tests/test_cli.py

Tests on TravisCI were failing because of the license check introduced with PR https://github.com/miykael/atlasreader/pull/71. This was the case for **general tests** (https://travis-ci.org/miykael/atlasreader/jobs/476838506) as well as for tests in the **notebook** (https://travis-ci.org/miykael/atlasreader/jobs/476838507).

Revert "ENH: Adds license message on first import"

---

.gitignore
atlasreader/__init__.py
requirements.txt

This PR continues the work under https://github.com/miykael/atlasreader/pull/71, by adding the license text to the `__init__.py` file. But in contrast to https://github.com/miykael/atlasreader/pull/71, this PR will not create an `.imported` file, but print the license text the first time the module is loaded within an environment.

Add license text from PR #71 to __init__

---

README.md
notebooks/atlasreader.ipynb

Hey everyone (@danjgale, @PeerHerholz, @rmarkello, @KirstieJane)
Thank you for all your hard work, support, motivation, inspiration and the overall energy that you put into this! I'm super excited that JOSS accepted the paper and that wouldn't have been possible without you!
The paper reference is the following:
Notter M. P., Gale D., Herholz P., Markello R. D., Notter-Bielser M.-L., & Whitaker K. (2019). AtlasReader: A Python package to generate coordinate tables, region labels, and informative figures from statistical MRI images. *Journal of Open Source Software, 4(34), 1257*, https://doi.org/10.21105/joss.01257.

Updating reference after JOSS publication

---

.zenodo.json
atlasreader/atlasreader.py

Dear all,
I found a bug for an edge condition in atlasreader. I think this is due to a rounding error (or rather no rounding but only changing float to integers without rounding at all). The two tables below show the peak table with the current implementation of atlasreader, where the Amygdala peak has a 1-p value of 0.  After implementing rounding of the coordinates the Amygdala gets the correct value of 1-p = 0.9996.
I hope this help,
Anna
Before the fix:
```
cluster_id	peak_x	peak_y	peak_z	peak_value	volume_mm	harvard_oxford
0	1	21.5	-12.5	-16.5	0.9998	6744	81% Right_Hippocampus
1	1	27.5	-34.5	-0.5	0.9990	6744	62% Right_Hippocampus
2	2	-24.5	-14.5	-16.5	0.9998	5816	92% Left_Hippocampus
3	2	-22.5	-6.5	-28.5	0.9812	5816	36% Left_Hippocampus; 30% …
```

[FIX] rounding issue 

---

.zenodo.json
atlasreader/atlasreader.py

Dear all,
first of all, thanks for this usefull tool! When I used the Harvard Oxford Atlas with a probability threshold of 25, I noticed that the probability threshold is not only used as a probability threshold for the atlas itself but the threshold also determines the minimum proportion of a cluster, which a region has to exceed to be part of the clusters.csv file. For instance a region encompassing 24% of a cluster would not be in the clusters.csv file after a probability threshold of 25 is applied. When changing the code according to the pull request, the region would be part of the clusters.csv file when a probility threshold of 0 or a threshold of 25 is applied. Only the proportion of the region would probably vary slightly, because of the different atlas probabilites used.
In my …

[FIX] probability threshold determines minimum proportion of a region of a cluster in clusters.csv

---

atlasreader/atlasreader.py

Hey there, 
I just started using the library and had trouble getting started (couldn't replicate the notebook). The issue had to do with the default value for `voxel_thresh`.
In particular when the default value is too high no voxel is selected and the error/warning is propagated down to nilearn and it was not immediatly clear to me what was causing the issue from `atlasreader`.
```
/~/workspace/test/venv/lib/python3.12/site-packages/nilearn/plotting/displays/_slicers.py:313: UserWarning: empty mask
ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
```
I've added an explicit warning in order to hopefully make things more clear
```
~/workspace/test/venv/lib/python3.12/site-packages/atlasreader/atlasreader.py:495: UserWarning: Threshold value '1.96' is greater than max …
```

explicit warning on voxel threshold too high
